security:
    hosts:
    - localhost
    - 10.22.40.132
    - 10.22.40.122
    - 10.22.40.62
    - 10.22.41.108 #Rosen
    - 10.22.41.73 #Toncho
    - 10.22.40.60

# HTTP Server
server:
  port: 4444  # HTTP (Tomcat) port

spring:
  application:
    name: admin-panel

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---
#spring:
#  profiles: cloud
#eureka:
#  instance:
#    hostname: ${APPLICATION_DOMAIN}
#    nonSecurePort: 80
#
#spring:
#  jpa:
#    generate-ddl: true