security:
    hosts:
    - localhost
    - 10.22.40.132
    - 10.22.40.122
    - 10.22.40.62
    - 10.22.41.108 #Rosen
    - 10.22.41.73 #Toncho
    - 10.22.40.60

# HTTP Server
server:
  port: 4444  # HTTP (Tomcat) port

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: admin-panel
  database:
    driverClassName: org.postgresql.ds.PGPoolingDataSource
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:5432/reservations
    username: postgres
    password: postgres1234
    className: rg.postgresql.ds.PGPoolingDataSource
  jackson:
    serialization:
      INDENT_OUTPUT: true
