# HTTP Server
server:
  port: 3333  # HTTP (Tomcat) port

eureka:
  instance:
     leaseRenewalIntervalInSeconds: 5   # DO NOT DO THIS IN PRODUCTION
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: reservations-service
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:5432/reservations
    username: postgres
    password: postgres1234
    driverClassName: org.postgresql.Driver
  jackson:
    serialization:
      INDENT_OUTPUT: true
