spring:
  application:
    name: reservations-app
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:5432/reservations
    username: postgres
    password: postgres1234
    driverClassName: org.postgresql.Driver
  jackson:
    serialization:
      INDENT_OUTPUT: true

security:
  basic:
    enabled: false

server:
  port: 2222   # HTTP (Tomcat) port

eureka:
  instance:
    hostname: reservations-app
    nonSecurePort: 80
    leaseRenewalIntervalInSeconds: 5
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
# Logging
logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG

multipart:
  maxFileSize: 100MB
  maxRequestSize: 100MB

